name: cert on 3 workers
on: {push: {branches: [cert-3workers]}}
jobs:
  cert:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Build chart dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build 5g-control-plane
          helm dependency build sdcore-helm-charts
      - uses: lfn-cnti/testsuite-action@05a9860905f31c6813f735d25e5cefd7c62a1e5a # v1.1.0
        with:
          version: v2.1.0
          cnf_config: .github/cnti/cnti-testsuite.yaml
          kind_config: .github/cnti/kind-3workers.yaml
          tests: cert
          fail_on_failure: false
